version: 0.0
os: linux

files:
  - source: app/
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: aws/scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: aws/scripts/start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: aws/scripts/validate_service.sh
      timeout: 300
      runas: root
